"""
Morpheus — Creative Discovery Pipeline
=========================================
Named for the Greek god of dreams. Controlled hallucination with
an absolute firewall between speculative and verified knowledge.

CRITICAL SAFETY RULE: Nothing generated by Morpheus EVER enters
Shadow's factual knowledge base without explicit human verification.
The firewall between speculative and verified knowledge is absolute.
Cerberus enforces this boundary.

Phase 1: Experiment tracking, evaluation tiers, SQLite persistence.
No overnight LLM execution yet (that's Phase 2).
"""

from __future__ import annotations

import json
import logging
import sqlite3
import time
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any

from modules.base import BaseModule, ModuleStatus, ToolResult

logger = logging.getLogger("shadow.morpheus")

# Valid experiment categories
VALID_CATEGORIES = {"optimization", "exploration", "comparison", "validation"}

# Valid status transitions
VALID_STATUSES = {"proposed", "running", "completed", "failed", "rejected"}

# Status transition rules: current_status -> set of allowed next statuses
VALID_TRANSITIONS = {
    "proposed": {"running", "rejected"},
    "running": {"completed", "failed"},
    "completed": set(),   # terminal — only evaluation updates score/tier
    "failed": set(),      # terminal
    "rejected": set(),    # terminal
}

# Evaluation tiers
TIER_LABELS = {
    1: "Breakthrough",
    2: "Useful",
    3: "Incremental",
    4: "Noise",
}


class Morpheus(BaseModule):
    """Creative discovery pipeline — experiment tracking and evaluation.

    Phase 1 builds the tracking infrastructure: propose experiments,
    run them, record results, evaluate outcomes. When the LLM pipeline
    comes online in Phase 2, everything is already wired.

    Everything Morpheus produces is quarantined as speculative content
    with trust_level=0.0. Only explicit user approval can promote
    speculative content to verified knowledge.
    """

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        """Initialize Morpheus.

        Args:
            config: Module configuration. Keys:
                - db_path: Path to SQLite DB (default: data/morpheus_experiments.db)
                - max_queue: Max experiments in overnight queue (default: 5)
        """
        super().__init__(
            name="morpheus",
            description="Creative discovery pipeline — experiment tracking and evaluation",
        )
        self._config = config or {}
        self._db_path = Path(
            self._config.get("db_path", "data/morpheus_experiments.db")
        )
        self._max_queue = int(self._config.get("max_queue", 5))
        self._conn: sqlite3.Connection | None = None

        # R&D Lab integration
        try:
            from modules.morpheus.rd_lab import RDLab
            self._rd_lab = RDLab(
                generate_fn=self._generate if hasattr(self, '_generate') else None,
                grimoire=self._grimoire if hasattr(self, '_grimoire') else None,
                experiment_store=self._experiment_store if hasattr(self, '_experiment_store') else None,
            )
        except ImportError:
            self._rd_lab = None

        # Self-improvement engine integration
        try:
            from modules.morpheus.self_improvement import SelfImprovementEngine
            self._self_improvement = SelfImprovementEngine(db_path=self._db_path)
        except Exception:
            self._self_improvement = None
            logger.debug("Self-improvement engine not available")

        # Prompt evolution engine
        try:
            from modules.morpheus.prompt_evolution import PromptEvolutionEngine
            from modules.morpheus.prompt_templates import PromptTemplateRegistry
            self._templates = PromptTemplateRegistry()
            self._evolution: PromptEvolutionEngine | None = None  # needs DB, set in initialize()
        except Exception:
            self._templates = None
            self._evolution = None
            logger.debug("Prompt evolution not available")

    async def initialize(self) -> None:
        """Start Morpheus. Create DB and tables."""
        self.status = ModuleStatus.STARTING
        try:
            self._db_path.parent.mkdir(parents=True, exist_ok=True)
            self._conn = sqlite3.connect(str(self._db_path))
            self._conn.execute("PRAGMA journal_mode=WAL")
            self._conn.execute("PRAGMA busy_timeout=5000")
            self._conn.row_factory = sqlite3.Row
            self._create_tables()

            # Initialize prompt evolution engine after tables exist
            if self._templates is not None:
                try:
                    from modules.morpheus.prompt_evolution import PromptEvolutionEngine
                    self._evolution = PromptEvolutionEngine(
                        db_path=self._db_path,
                        registry=self._templates,
                    )
                    # Reload persisted evolved templates into registry
                    for t in self._evolution.load_evolved_templates():
                        self._templates.add_template(t)
                except Exception as e:
                    self._evolution = None
                    logger.debug("Prompt evolution init failed: %s", e)

            self.status = ModuleStatus.ONLINE
            self._initialized_at = datetime.now()
            logger.info("Morpheus online. Experiment DB at %s", self._db_path)
        except Exception as e:
            self.status = ModuleStatus.ERROR
            logger.error("Morpheus failed to initialize: %s", e)
            raise

    def _create_tables(self) -> None:
        """Create the morpheus_experiments table."""
        if not self._conn:
            return
        self._conn.execute("""
            CREATE TABLE IF NOT EXISTS morpheus_experiments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                experiment_id TEXT UNIQUE NOT NULL,
                title TEXT NOT NULL,
                hypothesis TEXT NOT NULL,
                category TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'proposed',
                priority INTEGER DEFAULT 3,
                proposed_at TEXT NOT NULL,
                started_at TEXT,
                completed_at TEXT,
                input_data TEXT,
                result_data TEXT,
                evaluation_score REAL,
                evaluation_tier INTEGER,
                evaluation_notes TEXT,
                parent_experiment_id TEXT
            )
        """)
        self._conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_morpheus_status
            ON morpheus_experiments(status)
        """)
        self._conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_morpheus_category
            ON morpheus_experiments(category)
        """)
        self._conn.execute("""
            CREATE INDEX IF NOT EXISTS idx_morpheus_parent
            ON morpheus_experiments(parent_experiment_id)
        """)
        # Migration: add template_id column if missing (nullable for backward compat)
        try:
            self._conn.execute(
                "ALTER TABLE morpheus_experiments ADD COLUMN template_id TEXT"
            )
        except sqlite3.OperationalError:
            pass  # Column already exists
        self._conn.commit()

    async def execute(self, tool_name: str, params: dict[str, Any]) -> ToolResult:
        """Execute a Morpheus tool."""
        start = time.time()
        try:
            handlers = {
                "experiment_propose": self._experiment_propose,
                "experiment_start": self._experiment_start,
                "experiment_complete": self._experiment_complete,
                "experiment_evaluate": self._experiment_evaluate,
                "experiment_list": self._experiment_list,
                "experiment_queue": self._experiment_queue,
                "morpheus_report": self._morpheus_report,
                "prompt_evolve": self._prompt_evolve,
                "prompt_stats": self._prompt_stats,
                "self_improve_analyze": self._self_improve_analyze,
                "self_improve_proposals": self._self_improve_proposals,
            }

            handler = handlers.get(tool_name)
            if handler is None:
                result = ToolResult(
                    success=False, content=None, tool_name=tool_name,
                    module=self.name, error=f"Unknown tool: {tool_name}",
                )
            else:
                result = handler(params)

            result.execution_time_ms = (time.time() - start) * 1000
            self._record_call(result.success)
            return result

        except Exception as e:
            elapsed = (time.time() - start) * 1000
            self._record_call(False)
            logger.error("Morpheus tool '%s' failed: %s", tool_name, e)
            return ToolResult(
                success=False, content=None, tool_name=tool_name,
                module=self.name, error=str(e), execution_time_ms=elapsed,
            )

    async def shutdown(self) -> None:
        """Shut down Morpheus. Close DB connection."""
        if self._evolution is not None:
            try:
                self._evolution.close()
            except Exception:
                pass
            self._evolution = None
        if self._conn:
            self._conn.close()
            self._conn = None
        self.status = ModuleStatus.OFFLINE
        logger.info("Morpheus offline. DB connection closed.")

    def get_tools(self) -> list[dict[str, Any]]:
        """Return Morpheus's tool definitions."""
        return [
            {
                "name": "experiment_propose",
                "description": "Propose a new experiment for the discovery pipeline",
                "parameters": {
                    "title": "str — experiment title (required)",
                    "hypothesis": "str — what we expect to learn (required)",
                    "category": "str — optimization|exploration|comparison|validation (required)",
                    "priority": "int — 1-5, 1=highest (default 3)",
                    "input_data": "dict — input parameters for the experiment",
                    "parent_experiment_id": "str — UUID of parent experiment for follow-ups",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "experiment_start",
                "description": "Move a proposed experiment to running status",
                "parameters": {
                    "experiment_id": "str — UUID of experiment to start (required)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "experiment_complete",
                "description": "Record results for a running experiment",
                "parameters": {
                    "experiment_id": "str — UUID of experiment (required)",
                    "result_data": "dict — experiment results (required)",
                    "failed": "bool — mark as failed instead of completed (default false)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "experiment_evaluate",
                "description": "Score and tier a completed experiment",
                "parameters": {
                    "experiment_id": "str — UUID of experiment (required)",
                    "score": "float — 0.0-1.0 evaluation score (required)",
                    "tier": "int — 1=breakthrough, 2=useful, 3=incremental, 4=noise (required)",
                    "notes": "str — evaluation notes",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "experiment_list",
                "description": "List experiments with optional filters",
                "parameters": {
                    "status": "str — filter by status",
                    "category": "str — filter by category",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "experiment_queue",
                "description": "Get overnight experiment queue (proposed, sorted by priority)",
                "parameters": {
                    "max_items": "int — max items to return (default from config)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "morpheus_report",
                "description": "Compile experiment report for morning briefing",
                "parameters": {},
                "permission_level": "autonomous",
            },
            {
                "name": "prompt_evolve",
                "description": "Run an evolution cycle on prompt templates based on performance data",
                "parameters": {
                    "min_experiments": "int — minimum experiments since last evolution (default 10)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "prompt_stats",
                "description": "Show template performance stats — which templates produce the best ideas",
                "parameters": {
                    "template_id": "str — specific template ID for single-template stats (optional)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "self_improve_analyze",
                "description": "Analyze a Shadow module for improvement opportunities",
                "parameters": {
                    "module_name": "str — module codename (required)",
                    "source_path": "str — path to source file (default: modules/{module_name}/{module_name}.py)",
                },
                "permission_level": "autonomous",
            },
            {
                "name": "self_improve_proposals",
                "description": "List/filter improvement proposals",
                "parameters": {
                    "status": "str — filter by status",
                    "module": "str — filter by module name",
                },
                "permission_level": "autonomous",
            },
        ]

    # --- Tool implementations ---

    def _experiment_propose(self, params: dict[str, Any]) -> ToolResult:
        """Create a new experiment proposal.

        Args:
            params: title, hypothesis, category (required); priority, input_data,
                    parent_experiment_id (optional).
        """
        title = params.get("title", "").strip()
        hypothesis = params.get("hypothesis", "").strip()
        category = params.get("category", "").strip()
        priority = params.get("priority", 3)
        input_data = params.get("input_data")
        parent_id = params.get("parent_experiment_id")
        template_id = params.get("template_id")

        # Validation
        if not title:
            return ToolResult(
                success=False, content=None, tool_name="experiment_propose",
                module=self.name, error="Title is required",
            )
        if not hypothesis:
            return ToolResult(
                success=False, content=None, tool_name="experiment_propose",
                module=self.name, error="Hypothesis is required",
            )
        if category not in VALID_CATEGORIES:
            return ToolResult(
                success=False, content=None, tool_name="experiment_propose",
                module=self.name,
                error=f"Category must be one of: {', '.join(sorted(VALID_CATEGORIES))}. Got: {category}",
            )
        if not isinstance(priority, int) or priority < 1 or priority > 5:
            return ToolResult(
                success=False, content=None, tool_name="experiment_propose",
                module=self.name, error="Priority must be an integer 1-5",
            )

        # Validate parent exists if specified
        if parent_id and not self._get_experiment(parent_id):
            return ToolResult(
                success=False, content=None, tool_name="experiment_propose",
                module=self.name,
                error=f"Parent experiment {parent_id} not found",
            )

        # Auto-select template if not specified and evolution engine is available
        if template_id is None and self._evolution is not None:
            try:
                selected = self._evolution.select_template(category=category)
                template_id = selected["id"]
            except Exception:
                template_id = None

        experiment_id = str(uuid.uuid4())
        now = datetime.now().isoformat()

        input_json = None
        if input_data is not None:
            try:
                input_json = json.dumps(input_data)
            except (TypeError, ValueError) as e:
                return ToolResult(
                    success=False, content=None, tool_name="experiment_propose",
                    module=self.name, error=f"input_data not JSON-serializable: {e}",
                )

        self._conn.execute(
            """INSERT INTO morpheus_experiments
               (experiment_id, title, hypothesis, category, status, priority,
                proposed_at, input_data, parent_experiment_id, template_id)
               VALUES (?, ?, ?, ?, 'proposed', ?, ?, ?, ?, ?)""",
            (experiment_id, title, hypothesis, category, priority,
             now, input_json, parent_id, template_id),
        )
        self._conn.commit()

        experiment = self._get_experiment(experiment_id)
        logger.info("Experiment proposed: %s — %s", experiment_id[:8], title)

        return ToolResult(
            success=True, content=experiment,
            tool_name="experiment_propose", module=self.name,
        )

    def _experiment_start(self, params: dict[str, Any]) -> ToolResult:
        """Move an experiment from proposed to running.

        Args:
            params: experiment_id (required).
        """
        experiment_id = params.get("experiment_id", "").strip()
        if not experiment_id:
            return ToolResult(
                success=False, content=None, tool_name="experiment_start",
                module=self.name, error="experiment_id is required",
            )

        experiment = self._get_experiment(experiment_id)
        if not experiment:
            return ToolResult(
                success=False, content=None, tool_name="experiment_start",
                module=self.name, error=f"Experiment {experiment_id} not found",
            )

        current_status = experiment["status"]
        if "running" not in VALID_TRANSITIONS.get(current_status, set()):
            return ToolResult(
                success=False, content=None, tool_name="experiment_start",
                module=self.name,
                error=f"Cannot start experiment in '{current_status}' status. Must be 'proposed'.",
            )

        now = datetime.now().isoformat()
        self._conn.execute(
            "UPDATE morpheus_experiments SET status='running', started_at=? WHERE experiment_id=?",
            (now, experiment_id),
        )
        self._conn.commit()

        experiment = self._get_experiment(experiment_id)
        logger.info("Experiment started: %s", experiment_id[:8])

        return ToolResult(
            success=True, content=experiment,
            tool_name="experiment_start", module=self.name,
        )

    def _experiment_complete(self, params: dict[str, Any]) -> ToolResult:
        """Record results for a running experiment.

        Args:
            params: experiment_id, result_data (required); failed (optional bool).
        """
        experiment_id = params.get("experiment_id", "").strip()
        result_data = params.get("result_data")
        failed = params.get("failed", False)

        if not experiment_id:
            return ToolResult(
                success=False, content=None, tool_name="experiment_complete",
                module=self.name, error="experiment_id is required",
            )
        if result_data is None:
            return ToolResult(
                success=False, content=None, tool_name="experiment_complete",
                module=self.name, error="result_data is required",
            )

        experiment = self._get_experiment(experiment_id)
        if not experiment:
            return ToolResult(
                success=False, content=None, tool_name="experiment_complete",
                module=self.name, error=f"Experiment {experiment_id} not found",
            )

        target_status = "failed" if failed else "completed"
        current_status = experiment["status"]
        if target_status not in VALID_TRANSITIONS.get(current_status, set()):
            return ToolResult(
                success=False, content=None, tool_name="experiment_complete",
                module=self.name,
                error=f"Cannot complete experiment in '{current_status}' status. Must be 'running'.",
            )

        try:
            result_json = json.dumps(result_data)
        except (TypeError, ValueError) as e:
            return ToolResult(
                success=False, content=None, tool_name="experiment_complete",
                module=self.name, error=f"result_data not JSON-serializable: {e}",
            )

        now = datetime.now().isoformat()
        self._conn.execute(
            """UPDATE morpheus_experiments
               SET status=?, completed_at=?, result_data=?
               WHERE experiment_id=?""",
            (target_status, now, result_json, experiment_id),
        )
        self._conn.commit()

        experiment = self._get_experiment(experiment_id)
        logger.info("Experiment %s: %s", target_status, experiment_id[:8])

        return ToolResult(
            success=True, content=experiment,
            tool_name="experiment_complete", module=self.name,
        )

    def _experiment_evaluate(self, params: dict[str, Any]) -> ToolResult:
        """Score and tier a completed experiment.

        Tier 1 = Breakthrough, Tier 2 = Useful,
        Tier 3 = Incremental, Tier 4 = Noise.

        Args:
            params: experiment_id, score (0-1), tier (1-4), notes (optional).
        """
        experiment_id = params.get("experiment_id", "").strip()
        score = params.get("score")
        tier = params.get("tier")
        notes = params.get("notes", "")

        if not experiment_id:
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name, error="experiment_id is required",
            )
        if score is None:
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name, error="score is required",
            )
        if not isinstance(score, (int, float)) or score < 0.0 or score > 1.0:
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name, error="score must be a number between 0.0 and 1.0",
            )
        if tier not in {1, 2, 3, 4}:
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name, error=f"tier must be 1-4. Got: {tier}",
            )

        experiment = self._get_experiment(experiment_id)
        if not experiment:
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name, error=f"Experiment {experiment_id} not found",
            )

        if experiment["status"] != "completed":
            return ToolResult(
                success=False, content=None, tool_name="experiment_evaluate",
                module=self.name,
                error=f"Cannot evaluate experiment in '{experiment['status']}' status. Must be 'completed'.",
            )

        self._conn.execute(
            """UPDATE morpheus_experiments
               SET evaluation_score=?, evaluation_tier=?, evaluation_notes=?
               WHERE experiment_id=?""",
            (float(score), tier, notes, experiment_id),
        )
        self._conn.commit()

        experiment = self._get_experiment(experiment_id)
        tier_label = TIER_LABELS.get(tier, "Unknown")
        logger.info(
            "Experiment evaluated: %s — Tier %d (%s), score=%.2f",
            experiment_id[:8], tier, tier_label, score,
        )

        # Record outcome for prompt evolution if template was used
        exp_template_id = experiment.get("template_id") if experiment else None
        if exp_template_id and self._evolution is not None:
            try:
                self._evolution.record_outcome(
                    template_id=exp_template_id,
                    experiment_id=experiment_id,
                    tier=tier,
                    score=float(score),
                )
            except Exception as e:
                logger.debug("Failed to record evolution outcome: %s", e)

        return ToolResult(
            success=True, content=experiment,
            tool_name="experiment_evaluate", module=self.name,
        )

    def _experiment_list(self, params: dict[str, Any]) -> ToolResult:
        """List experiments with optional filters.

        Args:
            params: Optional 'status' and 'category' filters.
        """
        status_filter = params.get("status", "")
        category_filter = params.get("category", "")

        query = "SELECT * FROM morpheus_experiments WHERE 1=1"
        query_params: list[Any] = []

        if status_filter:
            if status_filter not in VALID_STATUSES:
                return ToolResult(
                    success=False, content=None, tool_name="experiment_list",
                    module=self.name,
                    error=f"Invalid status: {status_filter}. Valid: {', '.join(sorted(VALID_STATUSES))}",
                )
            query += " AND status=?"
            query_params.append(status_filter)

        if category_filter:
            if category_filter not in VALID_CATEGORIES:
                return ToolResult(
                    success=False, content=None, tool_name="experiment_list",
                    module=self.name,
                    error=f"Invalid category: {category_filter}. Valid: {', '.join(sorted(VALID_CATEGORIES))}",
                )
            query += " AND category=?"
            query_params.append(category_filter)

        query += " ORDER BY priority ASC, proposed_at DESC"

        rows = self._conn.execute(query, query_params).fetchall()
        experiments = [self._row_to_dict(row) for row in rows]

        return ToolResult(
            success=True,
            content={
                "experiments": experiments,
                "total": len(experiments),
                "filters": {
                    "status": status_filter or None,
                    "category": category_filter or None,
                },
            },
            tool_name="experiment_list",
            module=self.name,
        )

    def _experiment_queue(self, params: dict[str, Any]) -> ToolResult:
        """Get the overnight experiment queue.

        Returns proposed experiments sorted by priority, capped at max_queue.

        Args:
            params: Optional 'max_items' to override default cap.
        """
        max_items = params.get("max_items", self._max_queue)
        if not isinstance(max_items, int) or max_items < 1:
            max_items = self._max_queue

        rows = self._conn.execute(
            """SELECT * FROM morpheus_experiments
               WHERE status='proposed'
               ORDER BY priority ASC, proposed_at ASC
               LIMIT ?""",
            (max_items,),
        ).fetchall()

        experiments = [self._row_to_dict(row) for row in rows]

        # Count total proposed (may be more than returned)
        total_proposed = self._conn.execute(
            "SELECT COUNT(*) FROM morpheus_experiments WHERE status='proposed'"
        ).fetchone()[0]

        return ToolResult(
            success=True,
            content={
                "queue": experiments,
                "queue_size": len(experiments),
                "total_proposed": total_proposed,
                "max_queue": max_items,
            },
            tool_name="experiment_queue",
            module=self.name,
        )

    def _morpheus_report(self, params: dict[str, Any]) -> ToolResult:
        """Compile experiment report for morning briefing.

        Returns:
            - Completed experiments with tier 1-2 results (highlights)
            - Failed experiments with result data
            - Queue status (proposed count, running count)
        """
        # Tier 1-2 highlights: completed and evaluated with good results
        highlight_rows = self._conn.execute(
            """SELECT * FROM morpheus_experiments
               WHERE status='completed' AND evaluation_tier IN (1, 2)
               ORDER BY evaluation_tier ASC, evaluation_score DESC"""
        ).fetchall()
        highlights = [self._row_to_dict(row) for row in highlight_rows]

        # Failed experiments
        failed_rows = self._conn.execute(
            """SELECT * FROM morpheus_experiments
               WHERE status='failed'
               ORDER BY completed_at DESC"""
        ).fetchall()
        failed = [self._row_to_dict(row) for row in failed_rows]

        # Queue status counts
        status_counts = {}
        for row in self._conn.execute(
            "SELECT status, COUNT(*) as cnt FROM morpheus_experiments GROUP BY status"
        ).fetchall():
            status_counts[row["status"]] = row["cnt"]

        # Total experiments
        total = self._conn.execute(
            "SELECT COUNT(*) FROM morpheus_experiments"
        ).fetchone()[0]

        report = {
            "highlights": highlights,
            "highlight_count": len(highlights),
            "failed": failed,
            "failed_count": len(failed),
            "status_counts": status_counts,
            "total_experiments": total,
            "queue_size": status_counts.get("proposed", 0),
            "running_count": status_counts.get("running", 0),
        }

        logger.info(
            "Morpheus report: %d highlights, %d failed, %d in queue",
            len(highlights), len(failed), report["queue_size"],
        )

        return ToolResult(
            success=True, content=report,
            tool_name="morpheus_report", module=self.name,
        )

    def _prompt_evolve(self, params: dict[str, Any]) -> ToolResult:
        """Trigger an evolution cycle. Returns summary of new/retired templates.

        Args:
            params: Optional 'min_experiments' to override default threshold.
        """
        if self._evolution is None:
            return ToolResult(
                success=False, content=None, tool_name="prompt_evolve",
                module=self.name, error="Prompt evolution engine not available",
            )

        min_experiments = params.get("min_experiments", 10)
        if not isinstance(min_experiments, int) or min_experiments < 1:
            min_experiments = 10

        summary = self._evolution.evolve_cycle(min_experiments=min_experiments)
        return ToolResult(
            success=True, content=summary,
            tool_name="prompt_evolve", module=self.name,
        )

    def _prompt_stats(self, params: dict[str, Any]) -> ToolResult:
        """Show template performance stats.

        Args:
            params: Optional 'template_id' for single-template stats.
        """
        if self._evolution is None:
            return ToolResult(
                success=False, content=None, tool_name="prompt_stats",
                module=self.name, error="Prompt evolution engine not available",
            )

        template_id = params.get("template_id")
        all_stats = self._evolution.get_template_stats()

        if template_id:
            filtered = [s for s in all_stats if s["template_id"] == template_id]
            if not filtered:
                return ToolResult(
                    success=True,
                    content={"template_id": template_id, "stats": None, "message": "No performance data"},
                    tool_name="prompt_stats", module=self.name,
                )
            return ToolResult(
                success=True, content=filtered[0],
                tool_name="prompt_stats", module=self.name,
            )

        top = self._evolution.get_top_performers()
        under = self._evolution.get_underperformers()

        return ToolResult(
            success=True,
            content={
                "all_stats": all_stats,
                "top_performers": top,
                "underperformers": under,
                "total_templates": len(self._templates.get_all()) if self._templates else 0,
            },
            tool_name="prompt_stats", module=self.name,
        )

    # --- Internal helpers ---

    def _get_experiment(self, experiment_id: str) -> dict[str, Any] | None:
        """Fetch a single experiment by UUID."""
        if not self._conn:
            return None
        row = self._conn.execute(
            "SELECT * FROM morpheus_experiments WHERE experiment_id=?",
            (experiment_id,),
        ).fetchone()
        if row is None:
            return None
        return self._row_to_dict(row)

    def _row_to_dict(self, row: sqlite3.Row) -> dict[str, Any]:
        """Convert a sqlite3.Row to a dict, deserializing JSON fields."""
        d = dict(row)
        # Deserialize JSON fields
        for field in ("input_data", "result_data"):
            if d.get(field) is not None:
                try:
                    d[field] = json.loads(d[field])
                except (json.JSONDecodeError, TypeError):
                    pass  # Leave as string if not valid JSON
        return d

    # --- Self-improvement tool handlers ---

    def _self_improve_analyze(self, params: dict[str, Any]) -> ToolResult:
        """Analyze a Shadow module for improvement opportunities.

        Delegates to SelfImprovementEngine: runs static analysis then
        generates rule-based proposals.
        """
        if self._self_improvement is None:
            return ToolResult(
                success=False, content=None,
                tool_name="self_improve_analyze", module=self.name,
                error="Self-improvement engine not available",
            )

        module_name = params.get("module_name", "").strip()
        if not module_name:
            return ToolResult(
                success=False, content=None,
                tool_name="self_improve_analyze", module=self.name,
                error="module_name is required",
            )

        source_path = params.get("source_path", "").strip()
        if not source_path:
            source_path = f"modules/{module_name}/{module_name}.py"

        analysis = self._self_improvement.analyze_module(module_name, source_path)
        proposals = self._self_improvement.generate_proposals(
            module_name, source_path,
        )

        return ToolResult(
            success=True,
            content={
                "analysis": analysis,
                "proposals": proposals,
                "proposal_count": len(proposals),
            },
            tool_name="self_improve_analyze",
            module=self.name,
        )

    def _self_improve_proposals(self, params: dict[str, Any]) -> ToolResult:
        """List/filter improvement proposals.

        Delegates to SelfImprovementEngine.get_proposals().
        """
        if self._self_improvement is None:
            return ToolResult(
                success=False, content=None,
                tool_name="self_improve_proposals", module=self.name,
                error="Self-improvement engine not available",
            )

        status = params.get("status")
        module = params.get("module")

        proposals = self._self_improvement.get_proposals(
            status=status, module=module,
        )

        return ToolResult(
            success=True,
            content={"proposals": proposals, "count": len(proposals)},
            tool_name="self_improve_proposals",
            module=self.name,
        )
