"""
Morpheus — Creative Discovery Pipeline
=========================================
Named for the Greek god of dreams. Controlled hallucination with
an absolute firewall between speculative and verified knowledge.

CRITICAL SAFETY RULE: Nothing generated by Morpheus EVER enters
Shadow's factual knowledge base without explicit human verification.
The firewall between speculative and verified knowledge is absolute.
Cerberus enforces this boundary.

Phase 1: Queue management, tier evaluation, speculative storage
with trust_level=0.0. No overnight generation (needs LLM).
"""

import json
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Any

from modules.base import BaseModule, ModuleStatus, ToolResult

logger = logging.getLogger("shadow.morpheus")


class Morpheus(BaseModule):
    """Creative discovery pipeline. Controlled hallucination.

    Everything Morpheus produces is quarantined in the speculative
    partition with trust_level=0.0. Only explicit user approval
    can promote speculative content to verified knowledge.
    """

    # Tier definitions
    TIER_1 = 1  # Present first: high plausibility + high novelty
    TIER_2 = 2  # Worth reviewing: interesting but needs judgment
    TIER_3 = 3  # Interesting failure: the approach is informative
    TIER_4 = 4  # Archive: not useful this time

    VALID_TIERS = {1, 2, 3, 4}
    VALID_STATUSES = {"queued", "generating", "evaluating", "evaluated", "archived"}

    def __init__(self, config: dict[str, Any] | None = None) -> None:
        """Initialize Morpheus.

        Args:
            config: Module configuration.
        """
        super().__init__(
            name="morpheus",
            description="Creative discovery pipeline — controlled hallucination",
        )
        self._config = config or {}
        self._queue: list[dict[str, Any]] = []
        self._queue_file = Path(
            self._config.get("queue_file", "data/morpheus_queue.json")
        )
        self._next_id = 1

    async def initialize(self) -> None:
        """Start Morpheus. Load discovery queue."""
        self.status = ModuleStatus.STARTING
        try:
            self._load_queue()
            self.status = ModuleStatus.ONLINE
            logger.info(
                "Morpheus online. %d items in discovery queue.",
                len(self._queue),
            )
        except Exception as e:
            self.status = ModuleStatus.ERROR
            logger.error("Morpheus failed to initialize: %s", e)
            raise

    async def execute(self, tool_name: str, params: dict[str, Any]) -> ToolResult:
        """Execute a Morpheus tool."""
        start = time.time()
        try:
            handlers = {
                "discovery_queue_add": self._discovery_queue_add,
                "discovery_queue_list": self._discovery_queue_list,
                "discovery_evaluate": self._discovery_evaluate,
                "discovery_archive": self._discovery_archive,
                "speculative_store": self._speculative_store,
            }

            handler = handlers.get(tool_name)
            if handler is None:
                result = ToolResult(
                    success=False, content=None, tool_name=tool_name,
                    module=self.name, error=f"Unknown tool: {tool_name}",
                )
            else:
                result = handler(params)

            result.execution_time_ms = (time.time() - start) * 1000
            self._record_call(result.success)
            return result

        except Exception as e:
            elapsed = (time.time() - start) * 1000
            self._record_call(False)
            logger.error("Morpheus tool '%s' failed: %s", tool_name, e)
            return ToolResult(
                success=False, content=None, tool_name=tool_name,
                module=self.name, error=str(e), execution_time_ms=elapsed,
            )

    async def shutdown(self) -> None:
        """Shut down Morpheus. Save queue."""
        self._save_queue()
        self.status = ModuleStatus.OFFLINE
        logger.info("Morpheus offline. Queue saved.")

    def get_tools(self) -> list[dict[str, Any]]:
        """Return Morpheus's tool definitions."""
        return [
            {
                "name": "discovery_queue_add",
                "description": "Add topic to overnight discovery queue",
                "parameters": {"topic": "str", "source": "str", "context": "str"},
                "permission_level": "autonomous",
            },
            {
                "name": "discovery_queue_list",
                "description": "List queued discovery topics",
                "parameters": {"status_filter": "str"},
                "permission_level": "autonomous",
            },
            {
                "name": "discovery_evaluate",
                "description": "Evaluate a discovery by tier (1-4)",
                "parameters": {"discovery_id": "str", "tier": "int", "notes": "str"},
                "permission_level": "autonomous",
            },
            {
                "name": "discovery_archive",
                "description": "Archive evaluated discoveries",
                "parameters": {"discovery_id": "str"},
                "permission_level": "autonomous",
            },
            {
                "name": "speculative_store",
                "description": "Store speculative content with firewall flag",
                "parameters": {"content": "str", "topic": "str", "source_discovery_id": "str"},
                "permission_level": "autonomous",
            },
        ]

    # --- Tool implementations ---

    def _discovery_queue_add(self, params: dict[str, Any]) -> ToolResult:
        """Add a topic to the discovery queue.

        Args:
            params: 'topic' (required), 'source' (user/pattern/reaper), 'context'.
        """
        topic = params.get("topic", "")
        if not topic:
            return ToolResult(
                success=False, content=None, tool_name="discovery_queue_add",
                module=self.name, error="Topic is required",
            )

        discovery_id = str(self._next_id)
        self._next_id += 1

        item = {
            "id": discovery_id,
            "topic": topic,
            "source": params.get("source", "user"),
            "context": params.get("context", ""),
            "created_at": datetime.now().isoformat(),
            "status": "queued",
            "tier": None,
            "evaluation_notes": "",
            "speculative": True,  # FIREWALL: always True
            "trust_level": 0.0,   # FIREWALL: always 0.0
        }
        self._queue.append(item)
        self._save_queue()

        logger.info("Discovery queued: id=%s, topic=%s", discovery_id, topic[:50])

        return ToolResult(
            success=True,
            content=item,
            tool_name="discovery_queue_add",
            module=self.name,
        )

    def _discovery_queue_list(self, params: dict[str, Any]) -> ToolResult:
        """List items in the discovery queue.

        Args:
            params: Optional 'status_filter' to filter by status.
        """
        status_filter = params.get("status_filter", "")

        if status_filter and status_filter in self.VALID_STATUSES:
            items = [q for q in self._queue if q["status"] == status_filter]
        else:
            items = list(self._queue)

        return ToolResult(
            success=True,
            content={
                "items": items,
                "total": len(items),
                "by_status": self._count_by_status(),
            },
            tool_name="discovery_queue_list",
            module=self.name,
        )

    def _discovery_evaluate(self, params: dict[str, Any]) -> ToolResult:
        """Evaluate a discovery and assign a tier.

        Tier 1 = Present first, Tier 2 = Worth reviewing,
        Tier 3 = Interesting failure, Tier 4 = Archive.

        Args:
            params: 'discovery_id', 'tier' (1-4), 'notes'.
        """
        discovery_id = str(params.get("discovery_id", ""))
        tier = params.get("tier")
        notes = params.get("notes", "")

        if not discovery_id:
            return ToolResult(
                success=False, content=None, tool_name="discovery_evaluate",
                module=self.name, error="discovery_id is required",
            )

        if tier not in self.VALID_TIERS:
            return ToolResult(
                success=False, content=None, tool_name="discovery_evaluate",
                module=self.name,
                error=f"Tier must be 1-4. Got: {tier}",
            )

        item = self._find_item(discovery_id)
        if item is None:
            return ToolResult(
                success=False, content=None, tool_name="discovery_evaluate",
                module=self.name,
                error=f"Discovery {discovery_id} not found",
            )

        item["tier"] = tier
        item["evaluation_notes"] = notes
        item["status"] = "evaluated"
        item["evaluated_at"] = datetime.now().isoformat()
        # FIREWALL: trust level stays at 0.0 regardless of tier
        item["trust_level"] = 0.0
        item["speculative"] = True

        self._save_queue()
        logger.info("Discovery %s evaluated: tier=%d", discovery_id, tier)

        return ToolResult(
            success=True,
            content=item,
            tool_name="discovery_evaluate",
            module=self.name,
        )

    def _discovery_archive(self, params: dict[str, Any]) -> ToolResult:
        """Archive a discovery.

        Args:
            params: 'discovery_id'.
        """
        discovery_id = str(params.get("discovery_id", ""))
        if not discovery_id:
            return ToolResult(
                success=False, content=None, tool_name="discovery_archive",
                module=self.name, error="discovery_id is required",
            )

        item = self._find_item(discovery_id)
        if item is None:
            return ToolResult(
                success=False, content=None, tool_name="discovery_archive",
                module=self.name,
                error=f"Discovery {discovery_id} not found",
            )

        item["status"] = "archived"
        item["archived_at"] = datetime.now().isoformat()
        self._save_queue()

        return ToolResult(
            success=True,
            content=item,
            tool_name="discovery_archive",
            module=self.name,
        )

    def _speculative_store(self, params: dict[str, Any]) -> ToolResult:
        """Store speculative content with firewall enforcement.

        CRITICAL: trust_level is ALWAYS 0.0 and speculative is ALWAYS True.
        Nothing from Morpheus enters verified knowledge without user approval.

        Args:
            params: 'content', 'topic', optional 'source_discovery_id'.
        """
        content = params.get("content", "")
        topic = params.get("topic", "")

        if not content:
            return ToolResult(
                success=False, content=None, tool_name="speculative_store",
                module=self.name, error="Content is required",
            )

        if not topic:
            return ToolResult(
                success=False, content=None, tool_name="speculative_store",
                module=self.name, error="Topic is required",
            )

        entry = {
            "content": content,
            "topic": topic,
            "source_discovery_id": params.get("source_discovery_id"),
            "stored_at": datetime.now().isoformat(),
            "speculative": True,     # FIREWALL: non-negotiable
            "trust_level": 0.0,      # FIREWALL: non-negotiable
            "source_type": "morpheus_speculative",
            "verified": False,
        }

        logger.info("Speculative content stored: topic=%s", topic[:50])

        return ToolResult(
            success=True,
            content=entry,
            tool_name="speculative_store",
            module=self.name,
            metadata={"speculative": True, "trust_level": 0.0},
        )

    # --- Internal helpers ---

    def _find_item(self, discovery_id: str) -> dict[str, Any] | None:
        """Find a queue item by ID."""
        for item in self._queue:
            if item["id"] == str(discovery_id):
                return item
        return None

    def _count_by_status(self) -> dict[str, int]:
        """Count items by status."""
        counts: dict[str, int] = {}
        for item in self._queue:
            status = item.get("status", "unknown")
            counts[status] = counts.get(status, 0) + 1
        return counts

    def _load_queue(self) -> None:
        """Load discovery queue from disk."""
        if self._queue_file.exists():
            try:
                with open(self._queue_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                self._queue = data.get("queue", [])
                self._next_id = data.get("next_id", 1)
            except (json.JSONDecodeError, OSError):
                self._queue = []
                self._next_id = 1

    def _save_queue(self) -> None:
        """Persist discovery queue to disk."""
        self._queue_file.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "queue": self._queue,
            "next_id": self._next_id,
            "saved_at": datetime.now().isoformat(),
        }
        try:
            with open(self._queue_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2)
        except OSError as e:
            logger.error("Failed to save queue: %s", e)
