"""Tests for Sentinel Security Analyzer."""

from __future__ import annotations

import pytest
from unittest.mock import MagicMock

from modules.sentinel.security_analyzer import SecurityAnalyzer


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def analyzer() -> SecurityAnalyzer:
    """SecurityAnalyzer without Grimoire."""
    return SecurityAnalyzer()


@pytest.fixture
def analyzer_with_grimoire() -> SecurityAnalyzer:
    """SecurityAnalyzer with a mocked Grimoire."""
    grimoire = MagicMock()
    grimoire.remember.return_value = "test-uuid-1234"
    return SecurityAnalyzer(grimoire=grimoire)


# ---------------------------------------------------------------------------
# Sample configs
# ---------------------------------------------------------------------------

IPTABLES_CONFIG = """\
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
DROP       tcp  --  10.0.0.0/8           anywhere             tcp dpt:telnet
LOG        all  --  anywhere             anywhere             LOG level warning prefix "iptables_drop: "

Chain FORWARD (policy DROP)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
"""

IPTABLES_SAVE_CONFIG = """\
# Generated by iptables-save
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p tcp --dport 22 -m limit --limit 4/min -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
-A INPUT -s 10.0.0.0/8 -j DROP
-A INPUT -j LOG --log-prefix "drop: "
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
-A OUTPUT -p tcp --dport 53 -j ACCEPT
-A OUTPUT -p tcp --dport 443 -j ACCEPT
COMMIT
"""

UFW_CONFIG = """\
Status: active
Logging: on (low)

Default: deny (incoming), allow (outgoing), deny (routed)

                     To                         Action      From
                     --                         ------      ----
22/tcp                          ALLOW IN    Anywhere
80/tcp                          ALLOW IN    Anywhere
443/tcp                         ALLOW IN    Anywhere
22/tcp                          LIMIT IN    Anywhere
"""

NFTABLES_CONFIG = """\
table inet filter {
  chain input {
    type filter hook input priority 0; policy drop;

    iifname "lo" accept
    ct state established,related accept
    ct state invalid drop
    tcp dport 22 limit rate 4/minute accept
    tcp dport 80 accept
    tcp dport 443 accept
    ip protocol icmp icmp type echo-request limit rate 5/second accept
    ip saddr 10.0.0.0/8 drop
    log prefix "nft_drop: " counter drop
  }

  chain output {
    type filter hook output priority 0; policy drop;

    oifname "lo" accept
    ct state established,related accept
    tcp dport { 53, 80, 443 } accept
    udp dport { 53, 123 } accept
    log prefix "nft_out_drop: " counter drop
  }

  chain forward {
    type filter hook forward priority 0; policy drop;
  }
}
"""

PF_CONFIG = """\
ext_if = "em0"
set skip on lo

block all

pass in on $ext_if proto tcp from any to any port 22
pass in on $ext_if proto tcp from any to any port 80
pass out on $ext_if proto tcp from any to any port { 53, 80, 443 }
pass out on $ext_if proto udp from any to any port 53

antispoof for $ext_if
"""


# ---------------------------------------------------------------------------
# Tests: analyze_firewall_config
# ---------------------------------------------------------------------------

class TestAnalyzeFirewallConfig:
    """Tests for parsing firewall configs."""

    def test_parse_iptables_rules(self, analyzer: SecurityAnalyzer) -> None:
        """iptables -L output is parsed correctly."""
        result = analyzer.analyze_firewall_config(IPTABLES_CONFIG, "iptables")

        assert result["firewall_type"] == "iptables"
        assert result["default_policy"]["INPUT"] == "DROP"
        assert result["default_policy"]["FORWARD"] == "DROP"
        assert result["default_policy"]["OUTPUT"] == "ACCEPT"
        assert len(result["rules"]) > 0
        assert "ssh" in str(result["open_ports"]) or "22" in str(result["open_ports"]) or "http" in str(result["open_ports"])
        assert len(result["logging"]) > 0

    def test_parse_iptables_save(self, analyzer: SecurityAnalyzer) -> None:
        """iptables-save format is parsed correctly."""
        result = analyzer.analyze_firewall_config(IPTABLES_SAVE_CONFIG, "iptables")

        assert result["firewall_type"] == "iptables"
        assert "22" in str(result["open_ports"])
        assert "80" in str(result["open_ports"])
        # Anti-spoofing rule
        spoof_rules = [r for r in result["rules"] if "10.0.0.0" in str(r.get("source", ""))]
        assert len(spoof_rules) > 0
        # Logging
        assert len(result["logging"]) > 0

    def test_parse_ufw_status(self, analyzer: SecurityAnalyzer) -> None:
        """ufw status output is parsed correctly."""
        result = analyzer.analyze_firewall_config(UFW_CONFIG, "ufw")

        assert result["firewall_type"] == "ufw"
        assert result["default_policy"]["INPUT"] == "deny"
        assert result["default_policy"]["OUTPUT"] == "allow"
        assert "22" in str(result["open_ports"])
        assert "80" in str(result["open_ports"])
        assert "443" in str(result["open_ports"])
        assert len(result["logging"]) > 0

    def test_parse_nftables(self, analyzer: SecurityAnalyzer) -> None:
        """nftables config is parsed correctly."""
        result = analyzer.analyze_firewall_config(NFTABLES_CONFIG, "nftables")

        assert result["firewall_type"] == "nftables"
        assert result["default_policy"]["input"] == "drop"
        assert result["default_policy"]["output"] == "drop"
        assert len(result["rules"]) > 0
        assert len(result["logging"]) > 0

    def test_parse_pf(self, analyzer: SecurityAnalyzer) -> None:
        """pf.conf is parsed correctly."""
        result = analyzer.analyze_firewall_config(PF_CONFIG, "pf")

        assert result["firewall_type"] == "pf"
        assert "22" in str(result["open_ports"])
        assert "80" in str(result["open_ports"])
        assert len(result["rules"]) > 0

    def test_autodetect_iptables(self, analyzer: SecurityAnalyzer) -> None:
        """Auto-detects iptables from -L output."""
        result = analyzer.analyze_firewall_config(IPTABLES_CONFIG, "auto")
        assert result["firewall_type"] == "iptables"

    def test_autodetect_ufw(self, analyzer: SecurityAnalyzer) -> None:
        """Auto-detects ufw from status output."""
        result = analyzer.analyze_firewall_config(UFW_CONFIG, "auto")
        assert result["firewall_type"] == "ufw"

    def test_autodetect_nftables(self, analyzer: SecurityAnalyzer) -> None:
        """Auto-detects nftables from config."""
        result = analyzer.analyze_firewall_config(NFTABLES_CONFIG, "auto")
        assert result["firewall_type"] == "nftables"

    def test_autodetect_pf(self, analyzer: SecurityAnalyzer) -> None:
        """Auto-detects pf from config."""
        result = analyzer.analyze_firewall_config(PF_CONFIG, "auto")
        assert result["firewall_type"] == "pf"

    def test_unsupported_type(self, analyzer: SecurityAnalyzer) -> None:
        """Unsupported firewall type returns error."""
        result = analyzer.analyze_firewall_config("some config", "cisco_asa")
        assert "error" in result


# ---------------------------------------------------------------------------
# Tests: evaluate_firewall
# ---------------------------------------------------------------------------

class TestEvaluateFirewall:
    """Tests for firewall evaluation/scoring."""

    def test_default_deny_passes(self, analyzer: SecurityAnalyzer) -> None:
        """Default deny scores as pass."""
        analysis = analyzer.analyze_firewall_config(IPTABLES_CONFIG, "iptables")
        evaluation = analyzer.evaluate_firewall(analysis)

        # INPUT is DROP, FORWARD is DROP — at least partial
        dd = evaluation["checks"]["default_deny"]
        assert dd["status"] in ("pass", "partial")
        assert dd["score"] >= 2

    def test_default_accept_fails(self, analyzer: SecurityAnalyzer) -> None:
        """Default accept scores as fail."""
        config = """\
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
"""
        analysis = analyzer.analyze_firewall_config(config, "iptables")
        evaluation = analyzer.evaluate_firewall(analysis)

        assert evaluation["checks"]["default_deny"]["status"] == "fail"
        assert evaluation["checks"]["default_deny"]["score"] == 1

    def test_missing_egress_filtering(self, analyzer: SecurityAnalyzer) -> None:
        """Missing egress filtering is flagged."""
        config = """\
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh

Chain FORWARD (policy DROP)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
"""
        analysis = analyzer.analyze_firewall_config(config, "iptables")
        evaluation = analyzer.evaluate_firewall(analysis)

        egress = evaluation["checks"]["egress_filtering"]
        assert egress["status"] == "fail"
        assert egress["score"] == 1

    def test_good_config_gets_high_grade(self, analyzer: SecurityAnalyzer) -> None:
        """Well-configured firewall gets A or B grade."""
        analysis = analyzer.analyze_firewall_config(NFTABLES_CONFIG, "nftables")
        evaluation = analyzer.evaluate_firewall(analysis)

        assert evaluation["grade"] in ("A", "B")
        assert evaluation["total_score"] >= 18

    def test_evaluation_returns_recommendations(self, analyzer: SecurityAnalyzer) -> None:
        """Evaluation includes actionable recommendations."""
        config = """\
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
"""
        analysis = analyzer.analyze_firewall_config(config, "iptables")
        evaluation = analyzer.evaluate_firewall(analysis)

        assert len(evaluation["recommendations"]) > 0
        assert evaluation["grade"] in ("D", "F")

    def test_error_analysis_returns_error(self, analyzer: SecurityAnalyzer) -> None:
        """Evaluation of error analysis returns error."""
        result = analyzer.evaluate_firewall({"error": "bad config"})
        assert result["error"] == "bad config"


# ---------------------------------------------------------------------------
# Tests: explain_rule
# ---------------------------------------------------------------------------

class TestExplainRule:
    """Tests for rule explanation."""

    def test_explain_iptables_drop(self, analyzer: SecurityAnalyzer) -> None:
        """Explains an iptables DROP rule correctly."""
        result = analyzer.explain_rule(
            "iptables -A INPUT -p tcp --dport 23 -j DROP",
            "iptables",
        )

        assert result["original"] == "iptables -A INPUT -p tcp --dport 23 -j DROP"
        assert "DROP" in result["explanation"]
        assert "23" in result["explanation"]
        assert "tcp" in result["explanation"].lower() or "tcp" in result["explanation"]
        assert result["firewall_type"] == "iptables"

    def test_explain_provides_equivalents(self, analyzer: SecurityAnalyzer) -> None:
        """Rule explanation includes equivalents in other syntaxes."""
        result = analyzer.explain_rule(
            "iptables -A INPUT -p tcp --dport 22 -j ACCEPT",
            "iptables",
        )

        assert "nftables" in result["equivalents"]
        assert "ufw" in result["equivalents"]
        assert len(result["equivalents"]) >= 2

    def test_explain_nftables_rule(self, analyzer: SecurityAnalyzer) -> None:
        """Explains an nftables rule."""
        result = analyzer.explain_rule(
            "tcp dport 443 accept",
            "nftables",
        )

        assert "accept" in result["explanation"].lower()
        assert "443" in result["explanation"]
        assert "iptables" in result["equivalents"]

    def test_explain_ufw_rule(self, analyzer: SecurityAnalyzer) -> None:
        """Explains a ufw rule."""
        result = analyzer.explain_rule(
            "ufw allow 80/tcp",
            "ufw",
        )

        assert "allow" in result["explanation"].lower()
        assert "iptables" in result["equivalents"]

    def test_explain_pf_rule(self, analyzer: SecurityAnalyzer) -> None:
        """Explains a pf rule."""
        result = analyzer.explain_rule(
            "pass in on em0 proto tcp from any to any port 22",
            "pf",
        )

        assert "pass" in result["explanation"].lower()
        assert "22" in result["explanation"]
        assert "iptables" in result["equivalents"]

    def test_explain_broad_accept_raises_concern(self, analyzer: SecurityAnalyzer) -> None:
        """Broad accept rule flags concerns."""
        result = analyzer.explain_rule(
            "iptables -A INPUT -j ACCEPT",
            "iptables",
        )

        assert len(result["concerns"]) > 0


# ---------------------------------------------------------------------------
# Tests: generate_firewall
# ---------------------------------------------------------------------------

class TestGenerateFirewall:
    """Tests for firewall generation."""

    def test_generate_nftables_with_services(self, analyzer: SecurityAnalyzer) -> None:
        """Generates valid nftables config with required services."""
        result = analyzer.generate_firewall({
            "services": ["ssh", "http", "ollama"],
            "default_policy": "deny",
            "enable_logging": True,
            "rate_limit_ssh": True,
            "firewall_type": "nftables",
        })

        config = result["config_text"]
        assert "policy drop" in config
        assert "dport 22" in config
        assert "dport 80" in config
        assert "dport 11434" in config
        assert result["firewall_type"] == "nftables"
        assert result["security_score"] > 0

    def test_generate_includes_anti_spoofing(self, analyzer: SecurityAnalyzer) -> None:
        """Generated config includes anti-spoofing by default."""
        result = analyzer.generate_firewall({
            "services": ["ssh"],
            "default_policy": "deny",
            "firewall_type": "nftables",
        })

        config = result["config_text"]
        assert "bogons" in config or "10.0.0.0" in config

    def test_generate_includes_ssh_rate_limiting(self, analyzer: SecurityAnalyzer) -> None:
        """Generated config includes SSH rate limiting by default."""
        result = analyzer.generate_firewall({
            "services": ["ssh"],
            "default_policy": "deny",
            "rate_limit_ssh": True,
            "firewall_type": "nftables",
        })

        config = result["config_text"]
        assert "limit" in config.lower()
        assert "22" in config

    def test_generate_iptables(self, analyzer: SecurityAnalyzer) -> None:
        """Generates iptables config."""
        result = analyzer.generate_firewall({
            "services": ["ssh", "http"],
            "default_policy": "deny",
            "firewall_type": "iptables",
        })

        config = result["config_text"]
        assert "iptables" in config
        assert "-P INPUT DROP" in config
        assert "--dport 22" in config

    def test_generate_with_allowed_ips(self, analyzer: SecurityAnalyzer) -> None:
        """Generated config respects allowed IPs."""
        result = analyzer.generate_firewall({
            "services": ["ssh", "ollama"],
            "default_policy": "deny",
            "allowed_ips": ["192.168.1.100"],
            "firewall_type": "nftables",
        })

        config = result["config_text"]
        assert "192.168.1.100" in config

    def test_generate_returns_grade(self, analyzer: SecurityAnalyzer) -> None:
        """Generated config includes security grade."""
        result = analyzer.generate_firewall({
            "services": ["ssh"],
            "default_policy": "deny",
            "enable_logging": True,
            "rate_limit_ssh": True,
            "firewall_type": "nftables",
        })

        assert "grade" in result
        assert result["grade"] in ("A", "B", "C", "D", "F")


# ---------------------------------------------------------------------------
# Tests: compare_firewalls
# ---------------------------------------------------------------------------

class TestCompareFirewalls:
    """Tests for firewall comparison."""

    def test_compare_two_configs(self, analyzer: SecurityAnalyzer) -> None:
        """Compares two configs and returns structured comparison."""
        analysis1 = analyzer.analyze_firewall_config(IPTABLES_CONFIG, "iptables")
        analysis2 = analyzer.analyze_firewall_config(NFTABLES_CONFIG, "nftables")

        result = analyzer.compare_firewalls([analysis1, analysis2])

        assert "comparison" in result
        assert len(result["comparison"]) == 2
        assert "most_restrictive" in result
        assert "best_overall" in result
        assert "recommendation" in result

    def test_compare_needs_two(self, analyzer: SecurityAnalyzer) -> None:
        """Compare requires at least 2 configs."""
        result = analyzer.compare_firewalls([{"rules": []}])
        assert "error" in result


# ---------------------------------------------------------------------------
# Tests: learn_firewall_concepts
# ---------------------------------------------------------------------------

class TestLearnFirewallConcepts:
    """Tests for concept learning."""

    def test_learn_returns_structured_dict(self, analyzer: SecurityAnalyzer) -> None:
        """Learning returns complete structured knowledge."""
        result = analyzer.learn_firewall_concepts("stateful_vs_stateless")

        assert result["topic"] == "stateful_vs_stateless"
        assert "explanation" in result
        assert "how_it_works" in result
        assert "when_to_use" in result
        assert "shadow_relevance" in result
        assert "example_config" in result

    def test_learn_all_topics(self, analyzer: SecurityAnalyzer) -> None:
        """All defined topics return valid knowledge."""
        topics = [
            "stateful_vs_stateless", "dmz", "port_knocking", "fail2ban",
            "connection_tracking", "nat_types", "bridge_vs_route",
            "zone_based", "application_layer_filtering", "iptables_vs_nftables",
        ]
        for topic in topics:
            result = analyzer.learn_firewall_concepts(topic)
            assert "error" not in result, f"Topic {topic} returned error"
            assert result["topic"] == topic

    def test_learn_unknown_topic(self, analyzer: SecurityAnalyzer) -> None:
        """Unknown topic returns error with available list."""
        result = analyzer.learn_firewall_concepts("nonexistent_topic")
        assert "error" in result
        assert "available_topics" in result


# ---------------------------------------------------------------------------
# Tests: store_security_knowledge
# ---------------------------------------------------------------------------

class TestStoreSecurityKnowledge:
    """Tests for Grimoire storage."""

    def test_store_calls_grimoire(self, analyzer_with_grimoire: SecurityAnalyzer) -> None:
        """Store calls Grimoire.remember with correct params."""
        knowledge = {
            "topic": "test_topic",
            "explanation": "Test explanation",
            "how_it_works": "Test mechanism",
            "when_to_use": "Test scenario",
            "shadow_relevance": "Test relevance",
        }
        count = analyzer_with_grimoire.store_security_knowledge(knowledge, "test")

        assert count == 1
        analyzer_with_grimoire._grimoire.remember.assert_called_once()
        call_kwargs = analyzer_with_grimoire._grimoire.remember.call_args
        assert call_kwargs[1]["source_module"] == "sentinel"
        assert call_kwargs[1]["category"] == "security_knowledge"
        assert "firewall" in call_kwargs[1]["tags"]

    def test_store_deduplicates(self, analyzer_with_grimoire: SecurityAnalyzer) -> None:
        """Store passes check_duplicates=True to Grimoire."""
        knowledge = {"topic": "dup_test", "explanation": "Test"}
        analyzer_with_grimoire.store_security_knowledge(knowledge, "test")

        call_kwargs = analyzer_with_grimoire._grimoire.remember.call_args
        assert call_kwargs[1]["check_duplicates"] is True

    def test_store_without_grimoire(self, analyzer: SecurityAnalyzer) -> None:
        """Store without Grimoire returns 0."""
        count = analyzer.store_security_knowledge({"topic": "test"}, "test")
        assert count == 0

    def test_store_handles_grimoire_error(self, analyzer_with_grimoire: SecurityAnalyzer) -> None:
        """Store handles Grimoire errors gracefully."""
        analyzer_with_grimoire._grimoire.remember.side_effect = RuntimeError("DB error")
        count = analyzer_with_grimoire.store_security_knowledge(
            {"topic": "error_test", "explanation": "test"}, "test",
        )
        assert count == 0
